// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3dq8AwPOsofQ0z9OpftS_L_j10mcH0nE',
    appId: '1:997287507537:web:e4bdbc6415c7265a4e6a70',
    messagingSenderId: '997287507537',
    projectId: 'dak-ghar-25003',
    authDomain: 'dak-ghar-25003.firebaseapp.com',
    storageBucket: 'dak-ghar-25003.appspot.com',
    measurementId: 'G-LXQH60R0NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtperOVlzReRQ6MqT2B4ybZD1zgCJCLtI',
    appId: '1:997287507537:android:0891afac0f2b4c594e6a70',
    messagingSenderId: '997287507537',
    projectId: 'dak-ghar-25003',
    storageBucket: 'dak-ghar-25003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNlXANRzN7imguLFeUaLgPKcvGlXsEZ4',
    appId: '1:997287507537:ios:de6786c77c78b32c4e6a70',
    messagingSenderId: '997287507537',
    projectId: 'dak-ghar-25003',
    storageBucket: 'dak-ghar-25003.appspot.com',
    iosBundleId: 'com.example.dak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlNlXANRzN7imguLFeUaLgPKcvGlXsEZ4',
    appId: '1:997287507537:ios:de6786c77c78b32c4e6a70',
    messagingSenderId: '997287507537',
    projectId: 'dak-ghar-25003',
    storageBucket: 'dak-ghar-25003.appspot.com',
    iosBundleId: 'com.example.dak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3dq8AwPOsofQ0z9OpftS_L_j10mcH0nE',
    appId: '1:997287507537:web:ad1bb54933026ed64e6a70',
    messagingSenderId: '997287507537',
    projectId: 'dak-ghar-25003',
    authDomain: 'dak-ghar-25003.firebaseapp.com',
    storageBucket: 'dak-ghar-25003.appspot.com',
    measurementId: 'G-JZJG8XFGCP',
  );
}
